version: '3'

services:
  db:
    image: yobasystems/alpine-mariadb
    environment:
      MYSQL_ROOT_PASSWORD: filerun
      MYSQL_USER: filerun
      MYSQL_PASSWORD: filerun
      MYSQL_DATABASE: filerun
    #volumes:
    #  - /tmp/filerun/db:/var/lib/mysql

  web:
    build:
      context: web
      args:
        NG_VER: 1.1.4
    environment:
      FR_DB_HOST: db
      FR_DB_PORT: 3306
      FR_DB_NAME: filerun
      FR_DB_USER: filerun
      FR_DB_PASS: filerun
      APACHE_RUN_USER: www-data
      APACHE_RUN_USER_ID: 33
      APACHE_RUN_GROUP: www-data
      APACHE_RUN_GROUP_ID: 33
    depends_on:
      - db
    links:
      - db:db
    ports:
      - "6801:80"
    volumes:
    #  - /tmp/filerun/html:/var/www/html
      - /tmp/filerun/user-files:/user-files

  aria2:
    build:
      context: aria2
    environment:
      GID: 33
      UID: 33
    ports:
      - "6800:6800"
    volumes:
      - /tmp/filerun/user-files:/downloads