version: '3'

services:
  db:
    image: jbergstroem/mariadb-alpine
    environment:
      MYSQL_ROOT_PASSWORD: filerun
      MYSQL_USER: filerun
      MYSQL_PASSWORD: filerun
      MYSQL_DATABASE: filerun
    #volumes:
    #  - /tmp/filerun/db:/var/lib/mysql

  web:
    build:
      context: pan-web
      args:
        ENABLE_SSL:
        ENABLE_IMAGE_PREVIEW:
        ENABLE_VIDEO_PREVIEW:
        NG_VER: 1.1.4
    environment:
      ARIA2_HOST: aria2
      ARIA2_PORT: 6800
      ARIA2_RPC_SECRET: ""
      FR_DB_HOST: db
      FR_DB_PORT: 3306
      FR_DB_NAME: filerun
      FR_DB_USER: filerun
      FR_DB_PASS: filerun
      APACHE_RUN_USER: www-data
      APACHE_RUN_USER_ID: 33
      APACHE_RUN_GROUP: www-data
      APACHE_RUN_GROUP_ID: 33
    depends_on:
      - db
      - aria2
    links:
      - db:db
      - aria2:aria2
    ports:
      - "6801:80"
    #  - "6804:443"
    volumes:
    #  - /tmp/filerun/html:/var/www/html
      - /tmp/filerun/user-files:/user-files
    #  - /tmp/filerun/user-ssl:/user-ssl

  aria2:
    build:
      context: pan-dl
    environment:
      RPC_SECRET: ""
      GID: 33
      UID: 33
    #ports:
    #  - "6800:6800"
    volumes:
      - /tmp/filerun/user-files:/downloads